Code changes for complete flow of deployment of MAS Core or MAS Core+Manage and uninstall of deployment..
terraform-ibm-modules/terraform-ibm-mas pull request #42
Opened 2024-04-15 03:54 UTC by NatarajBTI

Code changes for complete flow of deployment of MAS Core or MAS Core+Manage and uninstall of deployment when Undeploy is clicked on UI.
/run pipeline

2024-04-15 03:56 UTC, NatarajBTI commented
/run pipeline

2024-04-18 02:55 UTC, NatarajBTI commented
/run pipeline

2024-04-18 02:58 UTC, padmankosalaram requested changes

2024-04-18 02:58 UTC, padmankosalaram commented on chart/deploy-mas/templates/02-uninstall-pre-delete.yaml
> +    checkov.io/skip1: CKV_K8S_20
@NatarajBTI Please check if we can fix these checkov violation if possible

2024-04-18 03:17 UTC, padmankosalaram commented on chart/deploy-mas/templates/02-uninstall-pre-delete.yaml
> +    checkov.io/skip1: CKV_K8S_20
@NatarajBTI build pipeline has failure, please check

2024-04-19 07:42 UTC, NatarajBTI commented
Code was checked in & merged in this PR --> https://github.com/terraform-ibm-modules/terraform-ibm-mas/pull/43. Hence closing this PR.

2024-04-19 07:42 UTC, closed without merging